### ISSUE TITLE
Unable to restore Hash Crack King challenges from backup

### ISSUE THREAD

**Issue by jtylers** [jtylers/CTFd_hash_crack_king#5]
ERROR:apscheduler.executors.default:Job "poll_kings (trigger: interval[0:01:00], next run at: 2018-03-19 11:08:43 MST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/CTFd/CTFd/plugins/CTFd_hash_crack_king/__init__.py", line 355, in poll_kings
    chal_king = c.king
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
    value = state._load_expired(state, passive)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 718, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
ObjectDeletedError: Instance '<HashCrackKingChallenge at 0x7f0eabf4ad50>' has been deleted, or its row is otherwise not present.

**Comment by jtylers** [comment]
This is a problem with the import/export tool in general:
https://github.com/CTFd/CTFd/issues/567

For now, I set up some tools that facilitate backing up and restoring your CTFd database:
https://github.com/jtylers/ctfd-tools
